# Stage 1
FROM rust:1.93 as builder
WORKDIR /app
COPY . .
RUN cargo build --release

# Stage 2 ON RECUPERE LE NOM DE LA release dans le tolm
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/zarC2 .
EXPOSE 8009
CMD ["./zarC2"]
