### Get all tasks
GET http://localhost:8009/task

### Add tasks
POST http://localhost:8009/task
Content-Type: application/json

[
	{
		"task_type":"ping",
        "task_options": {}
	}

]

### Add result
POST http://localhost:8009/results
Content-Type: application/json

[
{
    "task_id": "70127c72-008c-430f-9a3b-fb59f66be828",
    "success": true,
    "output": "PONG!",
    "execution_time_ms": 50
}  

]

### Get results
GET http://localhost:8009/results

### Get users
GET http://localhost:8009/users

### Get user by id
GET http://localhost:8009/user/1